Add backports for debian 10 & remove ubuntu 18.04
performous/performous-docker pull request #21
Opened 2022-10-08 13:39 UTC by Lord-Kamina

2022-10-08 18:14 UTC, ooshlablu requested changes

2022-10-08 18:14 UTC, ooshlablu commented on .github/workflows/docker.yml
> -          - 18.04
Ubuntu 18.04 is still supported until April 2023

2022-10-09 02:45 UTC, Lord-Kamina commented on .github/workflows/docker.yml
> -          - 18.04
I know, but #545 won't be able to build in 18.04 without using a PPA, because its version of boost is too old. I used ppas left and right on semaphore because we weren't distributing binaries. Are you ok doing that now?

2022-10-09 16:00 UTC, ooshlablu approved these changes

2022-10-09 16:43 UTC, merged